BiagioFesta/wtransport

- wtransport-proto/src/datagram.rs
- wtransport-proto/src/error.rs
- wtransport-proto/src/lib.rs
- wtransport/Cargo.toml
- wtransport/examples/server.rs
- wtransport/src/connection.rs
- wtransport/src/datagram.rs
- wtransport/src/engine/mod.rs
- wtransport/src/error.rs
- wtransport/src/lib.rs
> Dgrams support

- wtransport-proto/src/bytes.rs
- wtransport-proto/src/datagram.rs
- wtransport-proto/src/error.rs
- wtransport-proto/src/frame.rs
- wtransport-proto/src/headers.rs
- wtransport-proto/src/ids.rs
- wtransport-proto/src/lib.rs
- wtransport-proto/src/settings.rs
- wtransport-proto/src/stream.rs
- wtransport-proto/src/varint.rs
- wtransport/src/connection.rs
- wtransport/src/datagram.rs
- wtransport/src/engine/mod.rs
- wtransport/src/engine/session.rs
- wtransport/src/engine/stream.rs
- wtransport/src/engine/worker.rs
- wtransport/src/error.rs
Added strong types such as `VarInt` and code refactoring to be more readable and leverage rust type system
> Varint Refactoring

- wtransport/src/connection.rs
Fixes part of the request in https://github.com/BiagioFesta/wtransport/issues/5
> connection: method for remote address

- wtransport/src/stream.rs
Closes: https://github.com/BiagioFesta/wtransport/issues/21
> stream: stopped method on SendStream

- wtransport/src/config.rs
`allow_migration` for transport settings server config
> config: interface for migration setting on server side

- wtransport-proto/src/headers.rs
- wtransport/src/endpoint.rs
Fixes: https://github.com/BiagioFesta/wtransport/issues/38
> session_request: don't expose proto-headers, use std hashmap

- README.md
- wtransport/Cargo.toml
- wtransport/examples/client.rs
- wtransport/examples/server.rs
- wtransport/src/config.rs
- wtransport/src/endpoint.rs
- wtransport/src/lib.rs
Fixes: https://github.com/BiagioFesta/wtransport/issues/36
> API for configuring bind IP endpoint

- wtransport/src/datagram.rs
Requested from: https://github.com/BiagioFesta/wtransport/issues/51
> datagram: expose payload as Bytes

- wtransport/src/connection.rs
Fixes: https://github.com/BiagioFesta/wtransport/issues/53
> connection: close method

- wtransport/src/config.rs
Fixes: https://github.com/BiagioFesta/wtransport/issues/73
> Avoid overriding native store root with SSL_CERT_FILE env

- wtransport/Cargo.toml
- wtransport/examples/server.rs
- wtransport/src/config.rs
- wtransport/src/endpoint.rs
- wtransport/src/lib.rs
- wtransport/src/tls.rs
Fixes: https://github.com/BiagioFesta/wtransport/issues/81
> tls: make load Certificate async with tokio fs

- wtransport/src/config.rs
- wtransport/src/endpoint.rs
Fixes: https://github.com/BiagioFesta/wtransport/issues/87
> config: allow configuring DNS resolver for client::connect

- wtransport/src/tls.rs
Fixes: https://github.com/BiagioFesta/wtransport/issues/89
> tls: make Certificate clonable

- wtransport-proto/src/session.rs
- wtransport/src/endpoint.rs
- wtransport/src/error.rs
Fixes: https://github.com/BiagioFesta/wtransport/issues/91
> Add additional headers for connect

- wtransport/Cargo.toml
- wtransport/src/tls.rs
Fixes: https://github.com/BiagioFesta/wtransport/issues/103
> tls: put self-signed generation code behind default-on feature

- wtransport/src/error.rs
Fixes: https://github.com/BiagioFesta/wtransport/issues/116
> error: lower case error string msg

- wtransport/src/endpoint.rs
Reexport
* `Endpoint::close()`
* `Endpoint::reject_new_connections()`
> Reexport endpoint methods

- wtransport/src/config.rs
From this discussion: https://github.com/BiagioFesta/wtransport/pull/131#discussion_r1475555963
> tls: hashes verifier does not check PKI with native roots

- wtransport/src/stream.rs
Attempt for: https://github.com/BiagioFesta/wtransport/issues/134
> stream: implemented BiStream

- wtransport/src/endpoint.rs
Fixes #161
`cargo build` works. I didn't test it, per se.
> Fix #161 - add `SessionRequest::remote_address`

- wtransport/Cargo.toml
- wtransport/src/config.rs
- wtransport/src/tls.rs
Fixes: https://github.com/BiagioFesta/wtransport/issues/169
> Refactoring TLS module and pub expose TLS configurations

- wtransport/src/error.rs
Fixes: https://github.com/BiagioFesta/wtransport/issues/193
> error: getters for application close error

- wtransport/src/driver/streams/mod.rs
- wtransport/src/error.rs
- wtransport/src/stream.rs
Fixes: https://github.com/BiagioFesta/wtransport/issues/221
> send_stream: reset now reports specific error

- wtransport/src/connection.rs
Fixes: https://github.com/BiagioFesta/wtransport/issues/225
> connection: make it `Clone`

- wtransport/src/config.rs
- wtransport/src/endpoint.rs
This allows configuring `Endpoint` starting from an existing `UdpSocket`.
Drawback: client and server configurations are not `Clone` anymore, as they might carry bind socket now
> config: allows bind configuration with existing socket

- .github/workflows/ci.yml
- wtransport/Cargo.toml
- wtransport/src/tls.rs
Fixes: https://github.com/BiagioFesta/wtransport/issues/232
> support for aws-lc-rs/fips rustls-crypto-backend via cargo features

- wtransport/src/driver/utils.rs
Fixes: https://github.com/BiagioFesta/wtransport/issues/264
> fix_quinn_dependency
