wtransport/src/engine/stream.rs

Instead of forwarding poll_read() to the underlying quinn::RecvStream, it recursively called itself, causing a stack overflow.

Fix tokio::io::AsyncRead for QuicRecvStream

---

wtransport/src/endpoint.rs

Fixes: https://github.com/BiagioFesta/wtransport/issues/17
* Firefox correctly sends `user-agent` in its request.
* Chrome does not.
Exploit that to understand the origin of the request

endpoint: add chrome header support checking user-agent request

---

wtransport-proto/src/settings.rs
wtransport/src/driver/streams/settings.rs

Enable support for WebTransport over HTTP3 / draft 07
https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3-07
---
* Superseded: https://github.com/BiagioFesta/wtransport/pull/44
* Fixes: https://github.com/BiagioFesta/wtransport/issues/42
* Fixes: https://github.com/BiagioFesta/wtransport/issues/43

Support draft07

---

wtransport/Cargo.toml

When updating from wtransport 0.1.3 to 0.1.4, my build failed because wtransport used the old version of wtransport-proto (0.1.0). This PR should fix the version mismatch for anyone else updating from 0.1.3 to 0.1.4. wtransport's `-proto` dependency should also probably be kept in line with wtransport's own version.

Update wtransport's proto dependency to 0.1.4

---

wtransport-proto/src/stream.rs
wtransport/src/connection.rs
wtransport/src/datagram.rs
wtransport/src/driver/mod.rs
wtransport/src/driver/streams/mod.rs
wtransport/src/driver/utils.rs
wtransport/src/stream.rs

This allows clients to automatically derive Debug for types which embed wtransport types.
Fixes #58

Implement Debug for API types

---

clippy.toml

Without this configuration, clippy's `doc-markdown` lint will warn about this not being enclosed in backticks.

Allow "WebSocket" and "WebTransport" without backticks in doc comments.

---

wtransport/src/config.rs

Nothing is returned, so we should use a semicolon.

nit: Missing semicolon.

---

wtransport-proto/src/ids.rs

This is new in Rust 1.73. Details:
https://rust-lang.github.io/rust-clippy/master/index.html#/filter_map_bool_then

clippy: Fix filter_map_bool_then warning.

---

wtransport-proto/src/ids.rs
wtransport-proto/src/session.rs
wtransport/src/endpoint.rs

This is allowed in the current specification for when validating `ORIGIN` and deciding to reject the request.

Allow rejecting incoming session with forbidden.

---

wtransport/src/config.rs
wtransport/src/tls.rs

It seems a common use cases, that is, having access to the lower TLS configuration.
https://github.com/BiagioFesta/wtransport/issues/34
This is already possible by configuring QUIC layer (via feature `quinn`), however that requires an extra level of indirection.
I am not totally sure I want to have this in a stable API, mainly because it exposes lower dependency and potential silent-wrong configurations (wrong ALPN). However, it might be useful for now.

config: allow passing custom tls configuration

---

wtransport/src/config.rs

Not sure it's useful but it was useful for me! To inspect packets in Wireshark.

Add enable_key_log

---

wtransport-proto/Cargo.toml
wtransport-proto/src/frame.rs
wtransport-proto/src/headers.rs
wtransport-proto/src/lib.rs
wtransport-proto/src/qpack.rs
wtransport/src/driver/mod.rs
wtransport/src/endpoint.rs

Currently `wtransport` depends on [`ls-qpack-rs`](https://github.com/BiagioFesta/ls-qpack-rs) for *QPACK* implementation. However, `ls-qpack-rs` relies its *C* core-implementation and that implies compiling it requires some additional dependencies: *LLVM* (for `libclang`), *CMake* and, of course, a *C* compiler.
Those dependencies are thus transitively required by `wtransport`.
Especially on *Windows* (where dependencies are generally not distributed with a simple packager manager), compilation might not be super user-friendly. Some users were not clear about that requirements, and rightfully opened some issues. For example:
* https://github.com/BiagioFesta/ls-qpack-rs/issues/8
* https://github.com/BiagioFesta/ls-qpack-rs/issues/9
* https://github.com/BiagioFesta/ls-qpack-rs/issues/2
* …

Dedicated Inner QPACK protocol

---

wtransport/examples/full.rs
wtransport/src/config.rs
wtransport/src/tls.rs

New client TLS verifier which behaves similarly to serverCertificateHashes of W3C
Solves: https://github.com/BiagioFesta/wtransport/issues/128

tls: ServerHashVerification implementation

---

README.md
wtransport/Cargo.toml
wtransport/examples/full.rs
wtransport/examples/server.rs
wtransport/src/config.rs
wtransport/src/endpoint.rs
wtransport/src/lib.rs
wtransport/src/tls.rs

--- **This breaks API compatibility** ---
* `Certificate` was the union of a certificate chain and a private key.
```
use wtransport::Certificate;
let config = ServerConfig::builder()
.with_bind_default(4433)
.with_certificate(certificate)
.build();
```
Now stuff should be clearer,
* `Certificate` is just a single x509 certificate (which implements `Debug`)
* `Private Key` is a single private key.
* `Identity` is aggregation of multiple certificates (certificate chain) and a private key
- `Identity` implements `Debug` without leaking the private key.
```
use wtransport::Identity;
let config = ServerConfig::builder()
.with_bind_default(4433)
.with_identity(&identity)
.build();
```

TLS module refactoring

---

wtransport/src/tls.rs

not found error might be confused with a missing file rather than a missing valid private key within the PEM file
closes: https://github.com/BiagioFesta/wtransport/issues/151

tls: renamed not found private key error

---

wtransport/src/connection.rs
wtransport/src/error.rs
wtransport/src/tls.rs

Fixes: https://github.com/BiagioFesta/wtransport/issues/154 and https://github.com/BiagioFesta/wtransport/issues/155

TLS handshake data and keying material

---

wtransport/src/tls.rs

Context:
I'm storing the `Identity` in some configuration types that implement `Debug` and `Clone`; it would be very useful for me if I could just derive Clone on these types. This requires `Identity` to derive Clone as well.

Add Clone to Identity and PrivateKey

---

wtransport-proto/src/ids.rs
wtransport-proto/src/session.rs
wtransport/src/endpoint.rs

Fixes #163 by allowing HTTP 429 rejection.
`cargo build` works. I didn't test it, per se.

Fix #163 - add `SessionRequest::too_many_requests()`.

---

wtransport/src/connection.rs
wtransport/src/endpoint.rs

Fix #165 - document that IPv4 addresses from `remote_address` may be mapped to IPv6.

---

wtransport/Cargo.toml
wtransport/src/config.rs
wtransport/src/tls.rs

Removes `self-signed` feature for `with_server_certificate_hashes` TLS configuration.
This forces inclusion of `ring` dep
We might consider to change `dangerous` feature name in next dev

CertificateHash without self-signed feature

---

wtransport/Cargo.toml

This fixes the compilation process when no-default-features is specified
Fixes: https://github.com/BiagioFesta/wtransport/issues/180

fix: time dep is no more optional

---

wtransport-proto/src/error.rs
wtransport/src/error.rs

Overall this should improve the ergonomics of error handling. Eq/PartialEq is very useful for comparing errors with == instead of match statements. And Clone is necessary when needing to store an error (such as from a task), and repeatedly return it to the caller (such as when the struct is now poisoned to due a failed task).
<details>
<summary>More detail on why I needed this</summary>
I had a struct that communicated over channels to a tokio task. It would send and receive messages on a wtransport stream. If the task crashed due to a wtransport error, I returned the error via a tokio JoinHandle. 
In the struct when sending a message, if it detected that the task had died, it would return an error to the caller. I wanted to return the actual real error from wtransport, but that would …

Implement Eq, PartialEq, Clone for errors when possible

---

wtransport/src/config.rs

Pinning certs is not dangerous - the client is explicitly stating the identity of the server before connecting, so the need for a certificate authority is no longer necessary. This PR removes the `dangerous-configuration` feature gate on `with_server_certificate_hashes`. It also updates the docs to recommend using it over `with_no_cert_validation`.
For the equivalent browser APIs, both chromium and firefox implemented [serverCertificateHashes](https://developer.mozilla.org/en-US/docs/Web/API/WebTransport/WebTransport#browser_compatibility).

don't mark with_server_certificate_hashes as dangerous

---

wtransport/src/endpoint.rs

It seems to fix: https://github.com/BiagioFesta/wtransport/issues/166
`user-agent` does not contain `firefox` in new PROD versions.
Removing this proto draft negotiation, as it seems new PROD chrome versions do no require it anymore

endpoint/session: response will no longer include header draft hs

---

wtransport/Cargo.toml
wtransport/src/config.rs

This pull request introduces two new methods to the `ServerConfigBuilder`:
1. **`with_custom_transport`**: Allows configuration of a server with a custom transport setup while using a default TLS configuration generated from an `Identity`. This method provides flexibility for users who need to customize transport settings without manually configuring TLS.
2. **`with_custom_tls_and_transport`**: Enables full customization of both TLS and transport settings. Users can pass a preconfigured `TlsServerConfig` and a custom `TransportConfig` to fine-tune both layers of the server configuration. This is particularly useful for advanced scenarios where specific TLS and transport requirements are necessary.
Both methods come with comprehensive documentation and usage examples to help users …

add methods for custom transport configuration

---

wtransport/Cargo.toml
wtransport/src/config.rs
wtransport/src/connection.rs
wtransport/src/driver/streams/mod.rs
wtransport/src/driver/streams/qpack.rs
wtransport/src/driver/streams/settings.rs
wtransport/src/endpoint.rs
wtransport/src/error.rs
wtransport/src/stream.rs
wtransport/src/tls.rs

Fixes #121
Fixes #175
Supersedes #194 
I'm still new to `wtransport`, `quinn`, and `rustls`; this PR should be scrutinized for errors.
<details>
<summary>production deployments</summary>
</details>
```
- deps: update to quinn 0.11 and disable some default features by @finnbear in #200
- deps: update to rustls 0.23 and disable some default features by @finnbear in #200
- deps: update to rustls-pki-types 1.8 by @finnbear in #200
- Make `SendStream::reset` take a reference instead of ownership by @finnbear in #200
- docs: calling `priority` or `reset` after `reset` results in panic by @finnbear in #200
- Remove `Endpoint::reject_new_connections` by @finnbear in #200
- Add `Endpoint::open_connections` by @finnbear in #200
- Add multiple methods for `IncomingSession` for server, usable prior …
```

Upgrade to `rustls@0.23` and `quinn@0.11`

---

wtransport/Cargo.toml
wtransport/src/config.rs

To refresh TLS certificates, the `Endpoint` config must be reloaded. If the new config has a different (random) handshake token, then best case in-flight retries will fail. Worst case (as in my application), the *next* retry will fail regardless of when it happens.
```
- Add `ServerConfigBuilder::token_key` to avoid randomizing handshake token key by @finnbear in #201
```
Followup to #200
Example code for generating a handshake token:
```rust
fn generate_token_key() -> Arc<dyn quinn_proto::crypto::HandshakeTokenKey> {
use rand::RngCore;
let rng = &mut rand::thread_rng();
let mut master_key = [0u8; 64];
rng.fill_bytes(&mut master_key);
let master_key = ring::hkdf::Salt::new(ring::hkdf::HKDF_SHA256, &[]).extract(&master_key);
std::sync::Arc::new(master_key)
}
```
1. ~~should the example …

config/server: add `token_key` to avoid randomization of handshake token

---

wtransport/src/config.rs
wtransport/src/endpoint.rs

This PR aims to simplify (and minimize) `wtransport` configurations (both server and client).
In particular, it gives the possibility to configure a server and client directly passing the underlying transport configuration (i.e., `quinn`). This follows the same approach adopted for the underlying TLS stack (i.e. `rustls`).
Some advanced methods are been removed, such as: `token_key` and `enable_key_log` in the spirit of the mission of `wtransport`: having a minimal and user-friendly API. However, providing (with a single method) the configuration via `quinn` and `rustls` all advanced configurations are still possible.
This PR also changes `DnsResolver` interface: it simplifies the code and avoid usage of a `Mutex` for DNS resolution

Configuration simplification

---

wtransport/src/config.rs

Fixes: https://github.com/BiagioFesta/wtransport/issues/206

Constrain `DnsLookupFuture` to be `Send`

---

wtransport/Cargo.toml

Update to a version of `quinn` that enforces a version of `quinn-proto` that is patched against [ CVE-2024-45311](https://github.com/quinn-rs/quinn/security/advisories/GHSA-vr26-jcq5-fjj8#advisory-comment-108846).

deps: update to `quinn@0.11.5` (patched).

---

wtransport-proto/Cargo.toml
wtransport/Cargo.toml

* New release due to: [quinn/CVE-2024-45311](https://github.com/quinn-rs/quinn/security/advisories/GHSA-vr26-jcq5-fjj8)
* Major bump is required because of: https://github.com/BiagioFesta/wtransport/commit/f7e0374403aef026537d2dae208e159b24213b03

cargo: bump packages version 0.2.0 -> 0.3.0

---

wtransport/examples/full.rs

Fixes #219
`createBidirectionalStream` returns not `WebTransportReceiveStream` but `WebTransportBidirectionalStream`.
So, We have to pass `.readable`
ref: https://developer.mozilla.org/en-US/docs/Web/API/WebTransportBidirectionalStream
ref: [w3c/webtransport/samples/echo/client.js#72](https://github.com/w3c/webtransport/blob/3363834b7fcd5854aa8ef47c62881d9bf8c4eb2b/samples/echo/client.js#L72)
```sh
cargo run --example full
```
1. Click `Connect`
2. Select `Open a bidirectional stream`
3. Click `Send data` -> Receive ACK

examples: fix mismatched argument type

---

wtransport/Cargo.toml
wtransport/src/connection.rs

Expose the inner QUIC connection

---

wtransport/src/endpoint.rs

Right now `ConnectOptions` is effectively opaque, but I want to inspect it after creation so I can log the URL that it connects to. The user of my crate creates and passes their own `ConnectOptions`, so I'm unable to read the URL before creation.
This PR derives `Debug` so that it can be debug printed, and adds `url` and `additional_headers` read-only accessor fields. It also derives `Clone` so that I can reuse the options for later.
IMO, these two fields should just be public. I don't see a reason to keep them private since this struct is just a data container. But for consistency with the rest of the API, and to allow extending `ConnectOptions` in the future without breaking existing code, I've just written accessors for the fields individually.

Add Debug, Clone, and accessors on `ConnectOptions`

---

wtransport/Cargo.toml
wtransport/src/config.rs
wtransport/src/endpoint.rs

This PR exposes the `quinn::EndpointConfig` via `quic_endpoint_config`/`quic_endpoint_config_mut` on `ClientConfig`/`ServerConfig`, analogously to how `quinn::{Client,Server}` are currently exposed.
To give a bit of context to the use case: I'd like to manually manage connection IDs on the application level and would like to set the [`EndpointConfig::cid_generator`](https://github.com/quinn-rs/quinn/blob/ead9b9316c155073c0984a243aeb9b84c5465298/quinn-proto/src/config.rs#L651-L665) for that purpose.
If you have another proposal on how to expose this or don't like to expose it all, let me know. I just figured opening this PR was as quick as opening a discussion on what I'd like to change.

Expose `quinn::EndpointConfig` for `{Client,Server}Config`

---

README.md

This makes the emoji show up on https://crates.io/crates/wtransport .

Use Unicode emoji for crates.io compatibility

---

wtransport/src/config.rs

fixes https://github.com/BiagioFesta/wtransport/issues/248

Update `with_bind_socket` method to return `ClientConfigBuilder` instead of `ServerConfigBuilder`

---

README.md

thanks for your work!
i've made wtransport bindings for node.js, could they get added to the "other languages" section of this project's readme?

add node.js bindings link to readme

---

wtransport/src/driver/mod.rs
wtransport/src/driver/streams/connect.rs
wtransport/src/driver/streams/mod.rs

As discussed in #239, "finish means finish". Otherwise, when the client closes the connection, the server keeps waiting until max idle timeout.

No awaiting finish on supposed-to-be already finished connect_stream
